---
title: "MyFirstDashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ggplot2)
library(DT)
data = mpg
library(flexdashboard)
```

Page 1 - Sales {data-navmenu="Anual Report"}
======================================================================

Column 
----------------------------------------------------------------------
### Average Mlg

```{r}
avg.milage = round(mean(mtcars$mpg),2)

valueBox(avg.milage,icon = "fa-car",color = ifelse(avg.milage > 10,"warning","primary"))
```


### Average wt of car
```{r}
avg.wt = round(mean(mtcars$wt),2)

valueBox(avg.wt,icon = "fa-car",color = ifelse(avg.wt > 10,"warning","primary"))
```

Column {tabset}
-----------------------------------------------------------------------

### Chart B  

```{r}

data = head(mtcars,8)

datatable(data,options = list(bPaginate = F,pageLength = 4))

```
> this is the data of mtcars fjsdfwedwdjcjcjsdskcdjskcjsdc
csdsdfhsdjksdvvsdvhsd;jkv
csdvsdjcvsdjkvsdvjsdvjsd
scvsdcmsdkcmsdkvmsdmvsdv


### Chart C



Page 2 - Revenue
====================================================================

column
--------------------------------------------------------------------
### Chart B  Relation Between cty mlg and hgwy from each class mpg

```{r}


```
column
--------------------------------------------------------------------
### Chart C

```{r}

```
